language: go
go:
 - 1.6
sudo: required
services:
 - docker

script:
- golint `git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master) | grep ".go"`

notifications:

  slack: 'hyperledgerproject:azMP8Mw3cfGigXkqi5RujZXr'
  on_success: always
  on_failure: always
