obcca:
   image: obcca
   environment:
    - OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243
   command: obc-ca

cli:
  image: openchain-peer
  command: ./infiniteloop.sh
  environment:
    - OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243
    - OPENCHAIN_PEER_ADDRESSAUTODETECT=true
    - OPENCHAIN_SECURITY_ENABLED=true

vp0:
  extends:
    file: compose-consensus-4-defaults.yml
    service: vp
  environment:
    - OPENCHAIN_PEER_ID=vp0
    - OPENCHAIN_OBCPBFT_GENERAL_N=4
    - OPENCHAIN_PEER_VALIDATOR_REPLICAS_IPS=vp0:30303 vp1:30303 vp2:30303 vp3:30303
    - OPENCHAIN_SECURITY_ENROLLID=test_vp0
    - OPENCHAIN_SECURITY_ENROLLSECRET=MwYpmSRjupbT


vp1:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp1
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - OPENCHAIN_SECURITY_ENROLLID=test_vp1
    - OPENCHAIN_SECURITY_ENROLLSECRET=5wgHK9qqYaPy


vp2:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp2
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - OPENCHAIN_SECURITY_ENROLLID=test_vp2
    - OPENCHAIN_SECURITY_ENROLLSECRET=vQelbRvja7cJ


vp3:
  extends:
    service: vp0
  environment:
    - OPENCHAIN_PEER_ID=vp3
    - OPENCHAIN_PEER_DISCOVERY_ROOTNODE=vp0:30303
    - OPENCHAIN_SECURITY_ENROLLID=test_vp3
    - OPENCHAIN_SECURITY_ENROLLSECRET=9LKqKH5peurL
