vp:
  image:   openchain-peer
  environment:
    - OPENCHAIN_LOGGING_LEVEL=debug
    - OPENCHAIN_PEER_ADDRESSAUTODETECT=true
    - OPENCHAIN_PEER_VALIDATOR_CONSENSUS=obcpbft
    - OPENCHAIN_OBCPBFT_GENERAL_N=4
    - OPENCHAIN_OBCPBFT_GENERAL_TIMEOUT_REQUEST=10s
    - OPENCHAIN_VM_ENDPOINT=http://172.17.0.1:4243
    - OPENCHAIN_SECURITY_ENABLED=true
    - OPENCHAIN_PEER_PKI_ECA_PADDR=obcca:50051
    - OPENCHAIN_PEER_PKI_TCA_PADDR=obcca:50051
    - OPENCHAIN_PEER_PKI_TLSCA_PADDR=obcca:50051    
  command: obc-peer peer
