vp0:
  links:
    - membersrvc
  ports:
    - 5000:5000

vp1:
  links:
    - vp0
    - membersrvc

vp2:
  links:
    - vp0
    - membersrvc

vp3:
  links:
    - vp0
    - membersrvc

cli:
  links:
    - vp0
    - vp1
    - vp2
    - vp3
    - membersrvc
