vp:
  image:   hyperledger-peer
  environment:
    - CORE_LOGGING_LEVEL=debug
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
    - CORE_PBFT_GENERAL_N=4
    - CORE_PBFT_GENERAL_TIMEOUT_REQUEST=10s
    - CORE_VM_ENDPOINT=http://172.17.0.1:4243
    - CORE_SECURITY_ENABLED=true
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:50051
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:50051
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:50051
  command: peer peer
