vp0:
  environment:
    - CORE_PBFT_GENERAL_MODE=batch

vp1:
  environment:
    - CORE_PBFT_GENERAL_MODE=batch

vp2:
  environment:
    - CORE_PBFT_GENERAL_MODE=batch

vp3:
  environment:
    - CORE_PBFT_GENERAL_MODE=batch
