vp0:
  environment:
    - CORE_PBFT_GENERAL_MODE=classic

vp1:
  environment:
    - CORE_PBFT_GENERAL_MODE=classic

vp2:
  environment:
    - CORE_PBFT_GENERAL_MODE=classic

vp3:
  environment:
    - CORE_PBFT_GENERAL_MODE=classic
