// Code generated by protoc-gen-go.
// source: abac.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	abac.proto

It has these top-level messages:
	ABACMetadataEntry
	ABACMetadata
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ABACMetadataEntry is an entry within the metadata that store an attribute name with its respective key.
type ABACMetadataEntry struct {
	AttributeName string `protobuf:"bytes,1,opt,name=AttributeName" json:"AttributeName,omitempty"`
	AttributeKey  []byte `protobuf:"bytes,2,opt,name=AttributeKey,proto3" json:"AttributeKey,omitempty"`
}

func (m *ABACMetadataEntry) Reset()         { *m = ABACMetadataEntry{} }
func (m *ABACMetadataEntry) String() string { return proto.CompactTextString(m) }
func (*ABACMetadataEntry) ProtoMessage()    {}

// ABACMetadata hold both the original metadata bytes and the metadata required by the Attribute Based Access Control
type ABACMetadata struct {
	// Original metadata bytes
	Metadata []byte `protobuf:"bytes,1,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	// Entries for each attributes considered.
	Entries []*ABACMetadataEntry `protobuf:"bytes,2,rep,name=Entries" json:"Entries,omitempty"`
}

func (m *ABACMetadata) Reset()         { *m = ABACMetadata{} }
func (m *ABACMetadata) String() string { return proto.CompactTextString(m) }
func (*ABACMetadata) ProtoMessage()    {}

func (m *ABACMetadata) GetEntries() []*ABACMetadataEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}
