from hyperledger/fabric-baseimage:latest
RUN mkdir -p /var/hyperledger/db
ADD gopath.tar.bz2 $GOPATH/src/github.com/hyperledger/fabric
RUN go install github.com/hyperledger/fabric/_TARGET_
WORKDIR $GOPATH/src/github.com/hyperledger/fabric
