vp:
  image: hyperledger-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:4243
    # TODO:  This is currently required due to BUG in variant logic based upon log level.
    - CORE_LOGGING_LEVEL=DEBUG
  command: peer peer

membersrvc:
   image: membersrvc
   environment:
    - CORE_VM_ENDPOINT=http://172.17.0.1:4243
   command: membersrvc
