vp:
  image: hyperledger-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
    # TODO:  This is currently required due to BUG in variant logic based upon log level.
    - CORE_LOGGING_LEVEL=DEBUG
  # Startup of peer must be delayed to allow membersrvc to come up first
  command: sh -c "sleep 5; peer node start"

membersrvc:
   image: membersrvc
   environment:
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
   command: membersrvc
