vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_TLS_ENABLED=true
    - CORE_PEER_TLS_SERVERHOSTOVERRIDE=OBC
    - CORE_PEER_TLS_CERT_FILE=../bddtests/tlsca.cert
    - CORE_PEER_TLS_KEY_FILE=../bddtests/tlsca.priv

vp1:
  extends:
    service: vp0
  environment:
    - CORE_PEER_ID=vp1
    - CORE_PEER_DISCOVERY_ROOTNODE=vp0:30303
  links:
    - vp0
