sampleApp0:
  image: hyperledger-sdk-node
  environment:
    - MEMBERSRVC_ADDRESS=membersrvc0:50051
    - PEER_ADDRESS=vp0:30303
    - KEY_VALUE_STORE=/tmp/hl_sdk_node_key_value_store
  # Startup of peer must be delayed to allow membersrvc to come up first
  command: node sampleSDKApp
  links:
    - membersrvc0
    - vp0

